const words = [
    "apple",
    "banana",
    "grape",
    "orange",
    "kiwi",
    "mango",
    "strawberry",
    "computer",
    "keyboard",
    "monitor",
    "laptop",
    "mouse",
    "headphone",
    "smartphone",
    "guitar",
    "piano",
    "violin",
    "drums",
    "flute",
    "trumpet",
    "saxophone",
    "elephant",
    "tiger",
    "lion",
    "zebra",
    "giraffe",
    "kangaroo",
    "panda",
    "koala",
    "rabbit",
    "squirrel",
    "shark",
    "whale",
    "dolphin",
    "octopus",
    "penguin",
    "seal",
    "turtle",
    "crocodile",
    "lizard",
    "frog",
    "mountain",
    "valley",
    "river",
    "lake",
    "ocean",
    "desert",
    "forest",
    "meadow",
    "field",
    "hill",
    "sun",
    "moon",
    "stars",
    "planet",
    "galaxy",
    "comet",
    "asteroid",
    "blackhole",
    "nebula",
    "universe",
    "scooter",
    "bicycle",
    "car",
    "bus",
    "train",
    "plane",
    "helicopter",
    "submarine",
    "rocket",
    "ship",
    "soccer",
    "basketball",
    "baseball",
    "tennis",
    "volleyball",
    "rugby",
    "hockey",
    "cricket",
    "golf",
    "swimming",
    "dancing",
    "singing",
    "painting",
    "drawing",
    "sculpture",
    "photography",
    "acting",
    "writing",
    "reading",
    "music",
    "chocolate",
    "vanilla",
    "strawberry",
    "mint",
    "coffee",
    "caramel",
    "butter",
    "cheese",
    "cream",
    "cookie",
    "icecream",
    "pie",
    "cake",
    "brownie",
    "donut",
    "cupcake",
    "muffin",
    "cookie",
    "popcorn",
    "candy",
    "churros",
    "sunflower",
    "rose",
    "tulip",
    "lily",
    "daisy",
    "orchid",
    "cherryblossom",
    "violet",
    "magnolia",
    "cactus",
    "diamond",
    "ruby",
    "emerald",
    "sapphire",
    "gold",
    "silver",
    "platinum",
    "amethyst",
    "pearl",
    "opal",
    "carrot",
    "potato",
    "tomato",
    "onion",
    "garlic",
    "pepper",
    "spinach",
    "lettuce",
    "broccoli",
    "cucumber",
    "avocado",
    "mushroom",
    "eggplant",
    "beetroot",
    "peas",
    "corn",
    "zucchini",
    "pumpkin",
    "sweetpotato",
    "chili",
    "burger",
    "sandwich",
    "pizza",
    "sushi",
    "noodles",
    "pasta",
    "spaghetti",
    "lasagna",
    "soup",
    "salad",
    "steak",
    "chicken",
    "fish",
    "tofu",
    "egg",
    "cheeseburger",
    "fries",
    "tacos",
    "burrito",
    "wings",
    "flour",
    "sugar",
    "salt",
    "oil",
    "vinegar",
    "honey",
    "ketchup",
    "mustard",
    "mayonnaise",
    "hotdog",
    "soccer",
    "basketball",
    "baseball",
    "golf",
    "swimming",
    "fencing",
    "boxing",
    "wrestling",
    "karate",
    "taekwondo",
    "yoga",
    "pilates",
    "sprinting",
    "cycling",
    "hiking",
    "climbing",
    "skateboarding",
    "skiing",
    "snowboarding",
    "surfing",
    "woodpecker",
    "eagle",
    "hawk",
    "parrot",
    "pigeon",
    "crow",
    "sparrow",
    "robin",
    "owl",
    "flamingo",
    "alligator",
    "anteater",
    "armadillo",
    "bat",
    "beaver",
    "beetle",
    "bison",
    "buffalo",
    "camel",
    "capybara",
    "cheetah",
    "chimpanzee",
    "cougar",
    "cow",
    "coyote",
    "deer",
    "dingo",
    "dog",
    "donkey",
    "elephant",
    "ferret",
    "fox",
    "goat",
    "hamster",
    "hippopotamus",
    "horse",
    "hyena",
    "jaguar",
    "koala",
    "leopard",
    "lion",
    "meerkat",
    "moose",
    "mouse",
    "octopus",
    "otter",
    "owl",
    "panda",
    "parrot",
    "peacock",
    "penguin",
    "platypus",
    "rabbit",
    "raccoon",
    "rat",
    "reindeer",
    "seal",
    "shark",
    "sheep",
    "skunk",
    "sloth",
    "snake",
    "spider",
    "squirrel",
    "tiger",
    "tortoise",
    "vulture",
    "walrus",
    "whale",
    "wolf",
    "zebra",
    "eggplant",
    "papaya",
    "pineapple",
    "peach",
    "plum",
    "apricot",
    "blackberry",
    "blueberry",
    "watermelon",
    "pear",
    "pomegranate",
    "lychee",
    "cantaloupe",
    "grapefruit",
    "nectarine",
    "kumquat",
    "fig",
    "cherry",
    "passionfruit",
    "pistachio",
    "hazelnut",
    "almond",
    "walnut",
    "peanut",
    "cashew",
    "brazilnut",
    "macadamia",
    "pinecone",
    "acorn",
    "squirrel",
    "chipmunk",
    "bear",
    "moose",
    "beetle",
    "ant",
    "caterpillar",
    "butterfly",
    "moth",
    "ladybug",
];

let chosenWord = "";
let displayWord = "";
let attemptsLeft = 6;
let guessedLetters = [];

function startGame() {
    chosenWord = words[Math.floor(Math.random() * words.length)];
    displayWord = chosenWord
        .split("")
        .map(() => "_")
        .join(" ");
    document.getElementById("wordDisplay").textContent = displayWord;
    document.getElementById("attemptsLeft").textContent = attemptsLeft;
    document.getElementById("guessedLetters").textContent = guessedLetters.join(", ");
}

function guessLetter() {
    const inputField = document.getElementById("letterInput");
    const guessedLetter = inputField.value.toLowerCase();
    inputField.value = "";

    if (guessedLetter && !guessedLetters.includes(guessedLetter)) {
        guessedLetters.push(guessedLetter);
        updateGameState(guessedLetter);
    }
}

function updateGameState(letter) {
    if (chosenWord.includes(letter)) {
        displayWord = chosenWord
            .split("")
            .map((char, index) => (char === letter || displayWord[index * 2] !== "_" ? char : "_"))
            .join(" ");
        document.getElementById("wordDisplay").textContent = displayWord;
    } else {
        attemptsLeft--;
        document.getElementById("attemptsLeft").textContent = attemptsLeft;
        updateHangman();
    }

    document.getElementById("guessedLetters").textContent = guessedLetters.join(", ");
    checkGameStatus();
}

function updateHangman() {
    const hangmanDiv = document.getElementById("hangman");
    const stages = [
        ` O\n  |\n  |\n /|\\\n / \\`,
        ` O\n  |\n  |\n /|\\\n /  `,
        ` O\n  |\n  |\n /|\\`,
        ` O\n  |\n  |\n /|`,
        ` O\n  |\n  |`,
        ` O\n  |`,
        ` O`,
    ];

    hangmanDiv.innerHTML = `<pre>${stages[6 - attemptsLeft]}</pre>`;
}

function checkGameStatus() {
    if (attemptsLeft === 0) {
        alert("Game Over! You lost.");
        startGame();
    } else if (!displayWord.includes("_")) {
        alert("Congratulations! You won!");
        startGame();
    }
}

startGame();